Controllers/AnaSayfaController.cs
using KisiselWebSayfasi.Models.Siniflar;
using Microsoft.AspNetCore.Mvc;

namespace KisiselWebSayfasi.Controllers
{
    public class AnaSayfaController : Controller
    {
        //get:Anasayfa
        Context c=new Context();
        public IActionResult Index()
        {
            var deger=c.AnaSayfas.ToList();

            return View(deger);
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.VisualBasic;

namespace KisiselWebSayfasi.Controllers
{
    public class RoleController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Policy = "RequireManager")]
        public IActionResult Manager()
        {
            return View();
        }

        //[Authorize(Policy = "RequireAdmin")]
        [Authorize(Roles =$"{Constants.Roles.Administrator},{Constants.Roles.Manager}")]
            public IActionResult Admin()
        {
            return View();
        }
    }
}

Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="~/css/bootstrap.css" rel="stylesheet" />
    
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menüler</h3>
        <a href="/Admin/Index/" class="w3-bar-item w3-button">Bloglar </a>
        <a href="/AnaSayfa/Index/" class="w3-bar-item w3-button">Siteye Dön </a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h4>Admin Yönetim Paneli</h4>
        </div>
        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using KisiselWebSayfasi.Areas.Identity.Data
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KisiselWebSayfasi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KisiselWebSayfasi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KisiselWebSayfasi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/AnaSayfa/Index/">Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Sehrim/Index/">Şehrim</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/Blog/Index/">Blog</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area=""  asp-controller="Index" asp-action="Index">Index</a>
                             
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Index" asp-action="Admin">Index</a>
                             
                            </li>
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            2022 - KisiselWebSayfasi
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
</body>
</html>

Views/Shared/_TestLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using KisiselWebSayfasi.Areas.Identity.Data
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/anasayfa.css">
    <!-- Custom CSS -->
    <link href="~/css/anasayfa.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"><!--Font-->
    <script src="https://kit.fontawesome.com/95037e2c1d.js" crossorigin="anonymous"></script>
    <title>Web Programlama Projesi</title>
</head>


<body>
    <!--Menü Başlangıç-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-lightslategrey">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/AnaSayfa/Index/">Hakkımızda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Sehrim/Index/">Şehrim</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/Blog/Index/">Blog</a>
                    </li>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Yönetici
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="dropdown-item" href="/User/Index/">Kullanıcı Rol Güncelleme</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                                </li>
                            </ul>
                        </li>
                    }
                    @*
                     @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                    <a class="dropdown-item" href="/User/Index/">Kullanıcı Rol Güncelleme</a>
                             </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area=""  asp-controller="Role" asp-action="Index">Roles</a>
                             
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Admin">Admin</a>
                             
                            </li>
                        }
                    @*<li class="nav-item">
                        <a class="nav-link" href="/UserLogin/Login/">Oturum Aç</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Admin/AdminLogin/">Admin Giris</a>

                    </li>*@
                </ul>
            </div>
            <partial name="_LoginPartial" />
         </div>
    </nav>
    
    <!--Menü Bitiş-->
    @RenderBody()
    @await RenderSectionAsync("Scripts", required: false)
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - KisiselWebSayfasi - <a asp-area="" asp-controller="AnaSayfa" asp-action="Index">Privacy</a>
        </div>
    </footer>
</body>
</html>



